timezone: Europe/Rome
permalink: pretty
remote_theme: trasparente/mdr@gh-pages

# DEFAULTS
defaults:
  - scope:
      path: ''
    values:
      layout: default
      class: accent-pink

# COLLECTIONS
collections:
  cups:
    title: ğŸ†ï¸
    output: true
